// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeIeT0_DR05BldC-O90x9G_eRH3_pE66g',
    appId: '1:98334267162:web:ad5ce5a77913ca4b22fea3',
    messagingSenderId: '98334267162',
    projectId: 'music-bag-c9e21',
    authDomain: 'music-bag-c9e21.firebaseapp.com',
    storageBucket: 'music-bag-c9e21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxjYqEUukLzrwTiiQx46K5_JTF6lcFRrA',
    appId: '1:98334267162:android:bd6a2e43e911973822fea3',
    messagingSenderId: '98334267162',
    projectId: 'music-bag-c9e21',
    storageBucket: 'music-bag-c9e21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5lkcg0mzpn3e19Oj1RcqDqvey51AfJb0',
    appId: '1:98334267162:ios:dccefb1d5f114b7d22fea3',
    messagingSenderId: '98334267162',
    projectId: 'music-bag-c9e21',
    storageBucket: 'music-bag-c9e21.appspot.com',
    iosBundleId: 'com.example.musicPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5lkcg0mzpn3e19Oj1RcqDqvey51AfJb0',
    appId: '1:98334267162:ios:dccefb1d5f114b7d22fea3',
    messagingSenderId: '98334267162',
    projectId: 'music-bag-c9e21',
    storageBucket: 'music-bag-c9e21.appspot.com',
    iosBundleId: 'com.example.musicPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeIeT0_DR05BldC-O90x9G_eRH3_pE66g',
    appId: '1:98334267162:web:ee8192c9e5e60de822fea3',
    messagingSenderId: '98334267162',
    projectId: 'music-bag-c9e21',
    authDomain: 'music-bag-c9e21.firebaseapp.com',
    storageBucket: 'music-bag-c9e21.appspot.com',
  );
}
